version: "3"

services:
  devcontainer:
    container_name: devcontainer
    hostname: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - _USER=user
      - _UID=1000
      - _GID=1000
    ports:
      - "2222:22"
    volumes:
      - ./shared:/mnt/shared
